# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('hint', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FormElementInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('form_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FormElement')),
            ],
        ),
        migrations.CreateModel(
            name='FormElementListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('form_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FormElement')),
            ],
        ),
        migrations.CreateModel(
            name='FormElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.State')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forms.State')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.State')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Workflow'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Workflow'),
        ),
        migrations.AddField(
            model_name='formelementinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Workflow'),
        ),
        migrations.AddField(
            model_name='formelement',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FormElementType'),
        ),
        migrations.AddField(
            model_name='formelement',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Workflow'),
        ),
    ]
