# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='element_type',
            field=models.CharField(choices=[('text_field', 'Text Input'), ('number_input', 'Number Input'), ('option_group', 'Option Group'), ('text_area', 'Text Area')], max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='kind',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Intermediate', 'Intermediate'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=500),
        ),
    ]
