# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20161110_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='element_type',
            field=models.CharField(choices=[('text_input', 'Text Input'), ('number_input', 'Number Input'), ('option_group', 'Option Group'), ('text_area', 'Text Area')], max_length=50),
        ),
    ]
