# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20161110_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormElementType',
        ),
    ]
