# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('forms', '0005_auto_20161110_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='allowed_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
