# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_transition_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formelementinstance',
            name='workflow',
        ),
        migrations.AddField(
            model_name='formelementinstance',
            name='workflow_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.WorkflowInstance'),
            preserve_default=False,
        ),
    ]
