# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20161114_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_elements', to='forms.Workflow'),
        ),
        migrations.AlterField(
            model_name='formelementinstance',
            name='form_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='forms.FormElement'),
        ),
        migrations.AlterField(
            model_name='formelementinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_element_instances', to='forms.WorkflowInstance'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='forms.Workflow'),
        ),
    ]
