# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 14:02
from __future__ import unicode_literals

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20161114_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formelement',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='formelement',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
