# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20161117_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormElementInstance',
            new_name='FormElementEntry',
        ),
        migrations.RenameModel(
            old_name='WorkflowInstance',
            new_name='WorkflowEntry',
        ),
        migrations.RenameField(
            model_name='formelemententry',
            old_name='workflow_instance',
            new_name='workflow_entry',
        ),
    ]
