# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20161123_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelement',
            name='element_type',
            field=models.CharField(choices=[(b'text_input', b'Text Input'), (b'number_input', b'Number Input'), (b'date_input', b'Date Input'), (b'time_input', b'Time Input'), (b'date_time_input', b'Date Time Input'), (b'text_area', b'Text Area')], max_length=50),
        ),
    ]
