# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20161125_2316'),
        ('forms', '0010_auto_20161126_1941'),
    ]

    operations = [
    ]
