# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 08:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import reimbursement.models.medical.medical_detail.medical_detail
import reimbursement.models.medical.medical_detail.medicine_bill
import reimbursement.models.telephone_expense.bill.bill_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '0005_auto_20170507_0039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount_claimed_medicine', models.DecimalField(blank=True, decimal_places=2, help_text=b'The amount claimed for the medicines, if any', max_digits=12, null=True)),
                ('amount_claimed_test', models.DecimalField(blank=True, decimal_places=2, help_text=b'The amount claimed for the tests, if any', max_digits=12, null=True)),
                ('amount_claimed_room_rent', models.DecimalField(blank=True, decimal_places=2, help_text=b'The amount claimed for room rented, if any', max_digits=12, null=True)),
                ('amount_claimed_other', models.DecimalField(blank=True, decimal_places=2, help_text=b'Others, Ex :- Operation, Procedure, ICU / CCU/ Consultation / Others)', max_digits=12, null=True)),
                ('other_expenses', models.CharField(blank=True, help_text=b'Please specify, Ex :- Operation, Procedure, ICU / CCU/ Consultation / Others)', max_length=150, null=True)),
                ('amount_passed_medicine', models.DecimalField(blank=True, decimal_places=2, help_text=b'The amount passed for the medicines, if any', max_digits=12, null=True)),
                ('amount_passed_test', models.DecimalField(blank=True, decimal_places=2, help_text=b'The amount passed for the tests, if any', max_digits=12, null=True)),
                ('amount_passed_room_rent', models.DecimalField(blank=True, decimal_places=2, help_text=b'The amount passed for room rented, if any', max_digits=12, null=True)),
                ('amount_passed_other', models.DecimalField(blank=True, decimal_places=2, help_text=b'Others, Ex :- Operation, Procedure, ICU / CCU/ Consultation / Others)', max_digits=12, null=True)),
                ('total_amount_claimed', models.DecimalField(blank=True, decimal_places=2, help_text=b'Total amount claimed', max_digits=12)),
                ('total_amount_passed', models.DecimalField(blank=True, decimal_places=2, help_text=b'Total amount passed', max_digits=12)),
                ('total_amount_rejected', models.DecimalField(blank=True, decimal_places=2, help_text=b'Total amount rejected', max_digits=12)),
                ('medical_reimbursement_register_page_no', models.PositiveIntegerField(blank=True, help_text=b'Medical reimbursement register page number', null=True)),
                ('medical_reimbursement_register_sr_no', models.PositiveIntegerField(blank=True, help_text=b'Medical reimbursement register serial number', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(help_text=b'Enter bill number mentioned on the bill', max_length=10)),
                ('bill_date', models.DateField(help_text=b'Enter date mentioned on the bill')),
                ('date_from', models.DateField(help_text=b'Enter starting date of the billing')),
                ('date_to', models.DateField(help_text=b'Enter finishing date of the billing')),
                ('phone_number', models.CharField(help_text=b'Enter phone number', max_length=12, validators=[django.core.validators.RegexValidator(message=b'Phone number must be entered in the format', regex=b'^\\+?1?\\d{9,12}$')])),
                ('is_telephone_line', models.BooleanField(help_text=b'Is it a telephone number')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text=b'Amount mentioned on the bill', max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(help_text=b'Upload Image of bills', upload_to=reimbursement.models.telephone_expense.bill.bill_image.generate_filename)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text=b'Consultation Date')),
                ('fee', models.PositiveIntegerField(help_text=b'Consultation Fee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(help_text=b'Full name of the patient', max_length=150)),
                ('patient_age', models.PositiveSmallIntegerField(help_text=b'Age of the patient')),
                ('employee_relationship', models.CharField(help_text=b'Relationship with the employee', max_length=150)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text=b'Injection Date')),
                ('fee', models.PositiveIntegerField(help_text=b'Injection Fee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('general_detail', models.ForeignKey(help_text=b'General Detail', on_delete=django.db.models.deletion.CASCADE, to='reimbursement.GeneralDetail')),
            ],
            options={
                'verbose_name': 'Medical',
            },
        ),
        migrations.CreateModel(
            name='MedicalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('place_at_which_patient_fell_ill', models.CharField(help_text=b'Mention the place where the patient fell ill', max_length=150)),
                ('consultant_name', models.CharField(help_text=b'Full name of the medical officer', max_length=150)),
                ('consultant_designation', models.CharField(help_text=b'Designation of the medical officer', max_length=150)),
                ('consultant_hospital', models.CharField(help_text=b'Name of the hospital or dispensary', max_length=200)),
                ('consultation_place', models.CharField(help_text=b'Mention where consultation took place, for multiple places use commas', max_length=150)),
                ('injection_place', models.CharField(blank=True, help_text=b'Mention the place where injection held, for multiple places use commas', max_length=150, null=True)),
                ('diagnosis_place', models.CharField(blank=True, help_text=b'Mention the hospital or laboratory where diagnosis held', max_length=150, null=True)),
                ('diagnosis_advised', models.BooleanField(help_text=b'Whether the tests were under taken on the advice of the authorized medical attendant. If so certificate to the effect should be attached.')),
                ('diagnosis_advised_certificate', models.ImageField(blank=True, help_text=b'Upload Image of the certificate', null=True, upload_to=reimbursement.models.medical.medical_detail.medical_detail.diagnosis_advised_certificate_filename)),
                ('cost_of_medicines_market', models.PositiveIntegerField(blank=True, help_text=b'Mention cost of medicines purchased from market', null=True)),
                ('specialist_consultant_name', models.CharField(blank=True, help_text=b'Full name of the Specialist', max_length=150, null=True)),
                ('specialist_consultant_designation', models.CharField(blank=True, help_text=b'Designation of the Specialist', max_length=150, null=True)),
                ('specialist_consultant_hospital', models.CharField(blank=True, help_text=b'Name of the hospital or dispensary', max_length=200, null=True)),
                ('specialist_consultation_place', models.CharField(blank=True, help_text=b'Mention where consultation with the specialist took place', max_length=150, null=True)),
                ('total_amount_claimed', models.DecimalField(decimal_places=2, help_text=b'Mention total claim amount', max_digits=12)),
                ('less_advance_taken', models.DecimalField(blank=True, decimal_places=2, help_text=b'Mention Less advance taken before', max_digits=12, null=True)),
                ('net_amount_taken', models.DecimalField(decimal_places=2, help_text=b'Enter net amount, ie Total - Less Amount', max_digits=12)),
                ('medical', models.OneToOneField(help_text=b'Refers to Medical Model', on_delete=django.db.models.deletion.CASCADE, related_name='medical_detail', to='reimbursement.Medical')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalTransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('remarks', models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True)),
                ('approved_by', models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_user', to=settings.AUTH_USER_MODEL)),
                ('medical', models.ForeignKey(help_text=b'Medical', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_medical', to='reimbursement.Medical')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text=b'Name of the medicine', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text=b'Price of the medicine', max_digits=10)),
                ('medical_detail', models.ForeignKey(help_text=b'Model detail id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='reimbursement.MedicalDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(help_text=b'Upload Image of bills', upload_to=reimbursement.models.medical.medical_detail.medicine_bill.generate_filename)),
                ('medical_detail', models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine_bill', to='reimbursement.MedicalDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialistConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text=b'Specialist Consultation Date')),
                ('fee', models.PositiveIntegerField(help_text=b'Specialist Consultation Fee')),
                ('medical_detail', models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='specialist_consultation', to='reimbursement.MedicalDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('register_page_no', models.PositiveIntegerField(blank=True, help_text=b'Enter page number of the register', null=True)),
                ('register_serial_no', models.PositiveIntegerField(blank=True, help_text=b'Enter serial number for the record in the register', null=True)),
                ('amount_passed', models.DecimalField(blank=True, decimal_places=2, help_text=b'Enter the amount passed for reimbursement', max_digits=8, null=True)),
                ('state', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephone_expenses', to='erp_core.Employee')),
            ],
            options={
                'verbose_name': 'Telephone Expense',
            },
        ),
        migrations.CreateModel(
            name='TelephoneExpenseTransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True)),
                ('approved_by', models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_set', to=settings.AUTH_USER_MODEL)),
                ('telephone_expense', models.ForeignKey(help_text=b'Telephone Expense', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_set', to='reimbursement.TelephoneExpense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='injection',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='injection', to='reimbursement.MedicalDetail'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='reimbursement.MedicalDetail'),
        ),
        migrations.AddField(
            model_name='billimage',
            name='telephone_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_image_set', to='reimbursement.TelephoneExpense'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='telephone_expense',
            field=models.ForeignKey(help_text=b'Telephone Expense', on_delete=django.db.models.deletion.CASCADE, related_name='bill_detail_set', to='reimbursement.TelephoneExpense'),
        ),
        migrations.AddField(
            model_name='amountdetail',
            name='medical',
            field=models.OneToOneField(help_text=b'Refers to Medical Model', on_delete=django.db.models.deletion.CASCADE, related_name='amount_detail', to='reimbursement.Medical'),
        ),
    ]
