# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionaltour',
            options={'verbose_name': 'Professional Tour'},
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='amount_passed',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter amount that passed ', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='cheque_no',
            field=models.PositiveIntegerField(help_text=b'Enter cheque no.', null=True),
        ),
    ]
