# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaltour',
            name='advance_taken',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter the advance amount taken', max_digits=10),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='amount_passed',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter amount that passed ', max_digits=10),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter the amount spent on local journey', max_digits=10),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='approval',
            field=models.ImageField(blank=True, help_text=b'attach image of approval of director or HOD if obtained?', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter the amount paid for boarding and lodging', max_digits=10),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='fair_paid',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter the amount paid for fair for both ways', max_digits=10),
        ),
        migrations.AlterField(
            model_name='professionaltour',
            name='reimbursement_amount',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter the amount of reimbursement', max_digits=10),
        ),
    ]
