# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import reimbursement.models.telephone_expense.bill.bill_image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp_core', '0001_initial'),
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(help_text=b'Enter bill number mentioned on the bill', max_length=10)),
                ('bill_date', models.DateField(help_text=b'Enter date mentioned on the bill')),
                ('date_form', models.DateField(help_text=b'Enter starting date of the billing')),
                ('date_to', models.DateField(help_text=b'Enter finishing date of the billing')),
                ('phone_number', models.CharField(help_text=b'Enter phone number', max_length=12, validators=[django.core.validators.RegexValidator(message=b'Phone number must be entered in the format', regex=b'^\\+?1?\\d{9,12}$')])),
                ('is_telephone_line', models.BooleanField(help_text=b'Is it a telephone number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(help_text=b'Upload Image of bills', upload_to=reimbursement.models.telephone_expense.bill.bill_image.generate_filename)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelephoneExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('register_page_no', models.PositiveIntegerField(help_text=b'Enter page number of the register')),
                ('register_serial_no', models.PositiveIntegerField(help_text=b'Enter serial number for the record in the register')),
                ('amount_passed', models.DecimalField(decimal_places=2, help_text=b'Enter the amount passed for reimbursement', max_digits=8)),
                ('state', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephone_expenses', to='erp_core.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('remarks', models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True)),
                ('approved_by', models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='medicaldetail',
            name='less_amount_taken',
        ),
        migrations.AddField(
            model_name='medical',
            name='state',
            field=django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='medicaldetail',
            name='less_advance_taken',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Mention Less advance taken before', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='amountdetail',
            name='medical',
            field=models.OneToOneField(help_text=b'Refers to Medical Model', on_delete=django.db.models.deletion.CASCADE, related_name='amount_detail', to='reimbursement.Medical'),
        ),
        migrations.AlterField(
            model_name='amountdetail',
            name='medical_reimbursement_register_page_no',
            field=models.PositiveIntegerField(blank=True, help_text=b'Medical reimbursement register page number', null=True),
        ),
        migrations.AlterField(
            model_name='amountdetail',
            name='medical_reimbursement_register_sr_no',
            field=models.PositiveIntegerField(blank=True, help_text=b'Medical reimbursement register serial number', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='injection', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='general_detail',
            field=models.ForeignKey(help_text=b'General Detail', on_delete=django.db.models.deletion.CASCADE, to='reimbursement.GeneralDetail'),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='diagnosis_place',
            field=models.CharField(blank=True, help_text=b'Mention the hospital or laboratory where diagnosis held', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='injection_place',
            field=models.CharField(blank=True, help_text=b'Mention the place where injection held, for multiple places use commas', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='medical',
            field=models.OneToOneField(help_text=b'Refers to Medical Model', on_delete=django.db.models.deletion.CASCADE, related_name='medical_detail', to='reimbursement.Medical'),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='net_amount_taken',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter net amount, ie Total - Less Amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='specialist_consultant_designation',
            field=models.CharField(blank=True, help_text=b'Designation of the Specialist', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='specialist_consultant_hospital',
            field=models.CharField(blank=True, help_text=b'Name of the hospital or dispensary', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='specialist_consultant_name',
            field=models.CharField(blank=True, help_text=b'Full name of the Specialist', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='specialist_consultation_place',
            field=models.CharField(blank=True, help_text=b'Mention where consultation with the specialist took place', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='total_amount_claimed',
            field=models.DecimalField(decimal_places=2, help_text=b'Mention total claim amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Model detail id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine_bill', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='specialistconsultation',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='specialist_consultation', to='reimbursement.MedicalDetail'),
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='medical',
            field=models.ForeignKey(help_text=b'Medical', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_medical', to='reimbursement.Medical'),
        ),
        migrations.AddField(
            model_name='billimage',
            name='telephone_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_image_set', to='reimbursement.TelephoneExpense'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='telephone_expense',
            field=models.ForeignKey(blank=True, help_text=b'Telephone Expense', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_detail_set', to='reimbursement.TelephoneExpense'),
        ),
    ]
