# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_auto_20170506_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='telephone_expense',
            field=models.ForeignKey(help_text=b'Telephone Expense', on_delete=django.db.models.deletion.CASCADE, related_name='bill_detail_set', to='reimbursement.TelephoneExpense'),
        ),
    ]
