# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_auto_20170507_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text=b'Amount mentioned on the bill', max_digits=10),
        ),
    ]
