# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_auto_20170507_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField(help_text=b'Mention dates of meeting or conference')),
                ('professional', models.ForeignKey(help_text=b'', on_delete=django.db.models.deletion.CASCADE, to='reimbursement.ProfessionalTour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
