# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_medical_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountdetail',
            name='medical',
            field=models.OneToOneField(help_text=b'Refers to Medical Model', on_delete=django.db.models.deletion.CASCADE, related_name='amount_detail', to='reimbursement.Medical'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='injection', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='state',
            field=django_fsm.FSMField(blank=True, choices=[(b'Submitted', b'Submitted by employee'), (b'Verified by Dealing Assistant', b'Verified by Dealing Assistant'), (b'Verified by Medical Superintendent', b'Approved by Medical Superintendent'), (b'Approved by Deputy Registrar', b'Approved by Deputy Registrar'), (b'Approved by Senior Audit Officer.', b'Approved by Senior Audit Officer'), (b'Approved by Registrar', b'Approved by Registrar'), (b'Reimbursed---', b'Amount transferred by Accounts Department'), (b'Rejected', b'Reject')], default=b'Submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='medical',
            field=models.OneToOneField(help_text=b'Refers to Medical Model', on_delete=django.db.models.deletion.CASCADE, related_name='medical_detail', to='reimbursement.Medical'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Model detail id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='medicine_bill', to='reimbursement.MedicalDetail'),
        ),
        migrations.AlterField(
            model_name='specialistconsultation',
            name='medical_detail',
            field=models.ForeignKey(help_text=b'Medical detail id', on_delete=django.db.models.deletion.CASCADE, related_name='specialist_consultation', to='reimbursement.MedicalDetail'),
        ),
    ]
