# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:07
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_auto_20170501_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='state',
            field=django_fsm.FSMField(blank=True, choices=[(b'Submitted', b'Submitted by employee'), (b'Verified by Dealing Assistant', b'Verified by Dealing Assistant'), (b'Verified by Medical Superintendent', b'Approved by Medical Superintendent'), (b'Approved by Deputy Registrar', b'Approved by Deputy Registrar'), (b'Approved by Senior Audit Officer.', b'Approved by Senior Audit Officer'), (b'Approved by Registrar', b'Approved by Registrar'), (b'Reimbursed', b'Amount transferred by Accounts Department'), (b'Rejected', b'Reject')], default=b'Submitted', max_length=50),
        ),
    ]
