# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_meetingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingdate',
            old_name='meeting_date',
            new_name='meeting_dates',
        ),
    ]
