# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_auto_20170507_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephoneexpense',
            name='register_page_no',
            field=models.PositiveIntegerField(blank=True, help_text=b'Enter page number of the register', null=True),
        ),
        migrations.AlterField(
            model_name='telephoneexpense',
            name='register_serial_no',
            field=models.PositiveIntegerField(blank=True, help_text=b'Enter serial number for the record in the register', null=True),
        ),
    ]
