# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_auto_20170507_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdetail',
            old_name='date_form',
            new_name='date_from',
        ),
    ]
