# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_transitionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionhistory',
            name='medical',
        ),
        migrations.AddField(
            model_name='medical',
            name='transition_history',
            field=models.ManyToManyField(help_text=b'Medical Reimbursement', related_name='medical', to='reimbursement.TransitionHistory'),
        ),
    ]
