# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0007_auto_20170507_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephoneexpense',
            name='amount_passed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Enter the amount passed for reimbursement', max_digits=8, null=True),
        ),
    ]
