# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0008_auto_20170507_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneExpenseTransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True)),
                ('approved_by', models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_set', to=settings.AUTH_USER_MODEL)),
                ('telephone_expense', models.ForeignKey(help_text=b'Telephone Expense', on_delete=django.db.models.deletion.CASCADE, related_name='transition_history_set', to='reimbursement.TelephoneExpense')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
