# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0012_auto_20170503_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionhistory',
            name='medical',
        ),
    ]
