# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0015_transitionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionhistory',
            name='state_from',
        ),
        migrations.RemoveField(
            model_name='transitionhistory',
            name='state_to',
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='a',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
