# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0017_auto_20170503_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionhistory',
            name='medical',
            field=models.ManyToManyField(help_text=b'Medical Reimbursement', related_name='transition_history', to='reimbursement.Medical'),
        ),
    ]
