# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0018_transitionhistory_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transitionhistory',
            name='state_from',
        ),
        migrations.RemoveField(
            model_name='transitionhistory',
            name='state_to',
        ),
        migrations.RemoveField(
            model_name='transitionhistory',
            name='medical',
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='medical',
            field=models.ForeignKey(help_text=b'Medical', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_history', to='reimbursement.Medical'),
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='transition',
            field=models.ForeignKey(help_text=b'Transition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_history', to='reimbursement.Transition'),
        ),
    ]
