# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0019_auto_20170503_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionhistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b'Employee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
