# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0022_auto_20170503_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitionhistory',
            name='approved_by',
            field=models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='transition',
            field=models.ForeignKey(help_text=b'Transition', null=True, on_delete=django.db.models.deletion.CASCADE, to='reimbursement.Transition'),
        ),
    ]
