# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('reimbursement', '0023_auto_20170503_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionhistory',
            name='approved_by_group',
            field=models.ForeignKey(blank=True, help_text=b'Employee Group', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='remarks',
            field=models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True),
        ),
    ]
