# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0026_auto_20170503_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='medical',
            field=models.ManyToManyField(through='reimbursement.TransitionHistory', to='reimbursement.Medical'),
        ),
    ]
