# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0029_auto_20170503_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='medical',
            field=models.ManyToManyField(related_name='TMTM', through='reimbursement.TransitionHistory', to='reimbursement.Medical'),
        ),
    ]
