# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:42
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0032_auto_20170503_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='transitionhistory',
            name='transition',
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='state_from',
            field=django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='transitionhistory',
            name='state_to',
            field=django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50),
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
