# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0034_auto_20170503_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitionhistory',
            options={'ordering': ['created_at']},
        ),
    ]
