# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0035_auto_20170503_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitionhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
