# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0036_auto_20170503_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountdetail',
            name='medical_reimbursement_register_page_no',
            field=models.PositiveIntegerField(blank=True, help_text=b'Medical reimbursement register page number', null=True),
        ),
        migrations.AlterField(
            model_name='amountdetail',
            name='medical_reimbursement_register_sr_no',
            field=models.PositiveIntegerField(blank=True, help_text=b'Medical reimbursement register serial number', null=True),
        ),
    ]
