# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0037_auto_20170504_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionhistory',
            name='approved_by_group',
        ),
    ]
