# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0038_remove_transitionhistory_approved_by_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetail',
            name='less_amount_taken',
        ),
        migrations.AddField(
            model_name='medicaldetail',
            name='less_advance_taken',
            field=models.DecimalField(decimal_places=2, default=0, help_text=b'Mention Less advance taken before', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='net_amount_taken',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter net amount, ie Total - Less Amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='total_amount_claimed',
            field=models.DecimalField(decimal_places=2, help_text=b'Mention total claim amount', max_digits=12),
        ),
    ]
