# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0039_auto_20170505_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetail',
            name='less_advance_taken',
            field=models.DecimalField(decimal_places=2, help_text=b'Mention Less advance taken before', max_digits=12),
        ),
    ]
