# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0040_auto_20170505_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetail',
            name='diagnosis_advised',
            field=models.NullBooleanField(help_text=b'Whether the tests were under taken on the advice of the authorized medical attendant. If so certificate to the effect should be attached.'),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='diagnosis_place',
            field=models.CharField(blank=True, help_text=b'Mention the hospital or laboratory where diagnosis held', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='injection_place',
            field=models.CharField(blank=True, help_text=b'Mention the place where injection held, for multiple places use commas', max_length=150, null=True),
        ),
    ]
