# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0041_auto_20170505_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetail',
            name='diagnosis_advised',
            field=models.BooleanField(help_text=b'Whether the tests were under taken on the advice of the authorized medical attendant. If so certificate to the effect should be attached.'),
        ),
    ]
