# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseIndentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=200)),
                ('budget_head', models.CharField(max_length=50)),
                ('make_or_model_reason', models.TextField(max_length=500)),
                ('indenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
