# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-30 14:34
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='state',
            field=django_fsm.FSMField(blank=True, choices=[(b'Submitted', b'Submitted by Indentor'), (b'Approved by Head of Department', b'Approved by HOD'), (b'Approved by Junior Accounts Officer', b'Approved by Junior Accounts Officer'), (b'Approved by Deputy Registrar', b'Approved by Deputy Registrar'), (b'Rejected', b'Rejected')], default=b'Submitted', max_length=50),
        ),
    ]
