# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseindentrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='budgetary_approval',
            field=models.ImageField(blank=True, upload_to=b'budgetary_approval'),
        ),
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='directors_approval',
            field=models.ImageField(blank=True, upload_to=b'directors_approval'),
        ),
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='project_approval',
            field=models.ImageField(blank=True, upload_to=b'project_approval'),
        ),
        migrations.AlterField(
            model_name='purchaseindentrequest',
            name='state',
            field=django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50),
        ),
    ]
