# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20170501_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='amount_already_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='budget_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='budget_sanctioned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
