# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20170502_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('specification', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseIndentRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.EmailField(max_length=500)),
                ('email', models.TextField(max_length=50)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseIndentRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
