# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_department_hod'),
        ('purchase', '0005_item_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('remark', models.TextField(max_length=500)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_core.Employee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseIndentRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
