# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20170507_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='purchase_request',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[(b'lab_consumables', b'Lab Consumables'), (b'general_items', b'General Items'), (b'lab_equipments', b'Lab Equipment(s)'), (b'office_equipments', b'Office Equipment(s)'), (b'lab_furniture', b'Lab Furniture'), (b'office_furniture', b'Office Furniture')], default='general_items', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='purchase.Item'),
            preserve_default=False,
        ),
    ]
