# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20170507_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[(b'lab_consumables', b'Lab Consumables'), (b'general_items', b'General Items'), (b'lab_equipments', b'Lab Equipment(s)'), (b'office_equipments', b'Office Equipment(s)'), (b'lab_furniture', b'Lab Furniture'), (b'office_furniture', b'Office Furniture')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
