# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20170508_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='type',
            field=models.CharField(default='Others', max_length=50),
            preserve_default=False,
        ),
    ]
