# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseindentrequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[(b'Lab Consumables', b'Lab Consumables'), (b'General Items', b'General Items'), (b'Lab Equipment(s)', b'Lab Equipment(s)'), (b'Office Equipment(s)', b'Office Equipment(s)'), (b'Lab Furniture', b'Lab Furniture'), (b'Office Furniture', b'Office Furniture')], max_length=30),
        ),
    ]
