# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_auto_20170508_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseindentrequest',
            old_name='type',
            new_name='category',
        ),
    ]
