# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20170508_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseindentrequest',
            name='expenditure_debitable_to',
            field=models.CharField(default='Institute', max_length=100),
            preserve_default=False,
        ),
    ]
