# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text=b'Enter the date of booking')),
                ('from_time', models.TimeField(help_text=b'Enter the booking start time')),
                ('to_time', models.TimeField(help_text=b'Enter the booking end time')),
                ('purpose', models.CharField(help_text=b'Enter the purpose of booking', max_length=100)),
                ('laptop_req', models.IntegerField(help_text=b'Enter the number of laptops required')),
                ('projector_req', models.IntegerField(help_text=b'Enter the number of projectors required')),
                ('audio_req', models.IntegerField(help_text=b'Enter the number of audio systems required')),
                ('video_req', models.IntegerField(help_text=b'Enter the number of video conferencing systems required')),
                ('state', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_hall_booking', to='erp_core.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('remarks', models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True)),
                ('approved_by', models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, related_name='mp_hall_transition_history', to=settings.AUTH_USER_MODEL)),
                ('mp_hall', models.ForeignKey(help_text=b'MpHall', on_delete=django.db.models.deletion.CASCADE, related_name='mp_hall_transition_history', to='booking.MpHall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
