# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_from', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('state_to', django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50)),
                ('remarks', models.CharField(blank=True, help_text=b'Remarks', max_length=300, null=True)),
                ('approved_by', models.ForeignKey(help_text=b'Employee', on_delete=django.db.models.deletion.CASCADE, related_name='mp_hall_transition_history', to=settings.AUTH_USER_MODEL)),
                ('mp_hall', models.ForeignKey(help_text=b'MpHall', on_delete=django.db.models.deletion.CASCADE, related_name='mp_hall_transition_history', to='booking.MpHall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
