# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAllowanceAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('visit_purpose', models.CharField(help_text=b'Briefly describe the visit', max_length=100)),
                ('budget_head', models.CharField(help_text=b'Mention the budget head, for ex. Project/Institute/Any Other', max_length=100)),
                ('project_name', models.CharField(help_text=b'Mention the project name', max_length=100)),
                ('advance_amount_required', models.DecimalField(decimal_places=2, help_text=b'Enter the amount required in advance', max_digits=8)),
                ('bus_train_air_fare', models.DecimalField(decimal_places=2, help_text=b'Enter the fare amount as mentioned in the attached bill', max_digits=8)),
                ('taxi_fare', models.DecimalField(decimal_places=2, help_text=b'Enter the taxi fare amount, if any', max_digits=8)),
                ('food_expenses', models.DecimalField(decimal_places=2, help_text=b'Enter the food expenses', max_digits=8)),
                ('accomodation_charges', models.DecimalField(decimal_places=2, help_text=b'Enter the accomodation/hotel charges', max_digits=8)),
                ('project_no', models.IntegerField(help_text=b'Mention the project number')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text=b'Total reimbursed amount', max_digits=8)),
                ('funds_available', models.DecimalField(decimal_places=2, help_text=b'Amount of funds available under this budget head', max_digits=8)),
                ('amount_passed', models.DecimalField(decimal_places=2, help_text=b'Mention the amount sanctioned', max_digits=8)),
                ('letter', models.ImageField(help_text=b'Attach image of the recommendation or invitation letter', upload_to=b'')),
                ('fare', models.ImageField(blank=True, help_text=b'Attach image of bus/air/train ticket', null=True, upload_to=b'')),
                ('registration_fee', models.ImageField(blank=True, help_text=b'Attach image of registration fee', null=True, upload_to=b'')),
                ('state', django_fsm.FSMField(blank=True, default=(b'submitted',), max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
