# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_allowance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text=b'Mention the date of journey')),
                ('from_place', models.CharField(help_text=b'Place from where flight/train/bus started', max_length=100)),
                ('to_place', models.CharField(help_text=b'Place where flight/train/bus stopped', max_length=100)),
                ('travel_mode', models.CharField(help_text=b'Mention the mode of travel', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='travelallowanceadvance',
            name='registration_image',
            field=models.ImageField(blank=True, help_text=b'Attach image of registration fee', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='travelallowanceadvance',
            name='fare',
            field=models.ImageField(help_text=b'Attach image of bus/air/train ticket', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='travelallowanceadvance',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, help_text=b'Enter the registration fee as mentioned in attachment', max_digits=8),
        ),
    ]
