# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_allowance', '0002_auto_20170506_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelallowanceadvance',
            name='registration_image',
            field=models.ImageField(help_text=b'Attach image of registration fee', upload_to=b''),
        ),
    ]
