# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
        ('advance_allowance', '0005_auto_20170506_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetails',
            name='Employee',
            field=models.ForeignKey(blank=True, help_text=b'Employee Detail', null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.Employee'),
        ),
    ]
