# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advance_allowance', '0006_traveldetails_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='Employee',
            field=models.ForeignKey(help_text=b'Employee Detail', on_delete=django.db.models.deletion.CASCADE, to='erp_core.Employee'),
        ),
    ]
