# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advance_allowance', '0007_auto_20170506_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldetails',
            name='Employee',
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='travel_allowance_advance',
            field=models.ForeignKey(blank=True, help_text=b'Travel Detail', null=True, on_delete=django.db.models.deletion.CASCADE, to='advance_allowance.TravelAllowanceAdvance'),
        ),
    ]
