# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:15
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('advance_allowance', '0008_auto_20170506_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelallowanceadvance',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='travelallowanceadvance',
            name='state',
            field=django_fsm.FSMField(blank=True, default=b'Submitted', max_length=50, null=True),
        ),
    ]
