# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advance_allowance', '0009_auto_20170506_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='travel_allowance_advance',
            field=models.ForeignKey(help_text=b'Travel Detail', on_delete=django.db.models.deletion.CASCADE, to='advance_allowance.TravelAllowanceAdvance'),
        ),
    ]
