from dealing_assistant import generate_state_change_dealing_assistant
from medical_superintendent import generate_state_change_medical_superintendent
from deputy_registrar import generate_state_change_deputy_registrar
from senior_audit_officer import generate_state_change_senior_audit_officer
from registrar import generate_state_change_registrar
from junior_accounting_officer import generate_state_change_junior_accounting_officer
