# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text=b'Head of the Department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
