# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_department_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text=b'Head of the Department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_set', to='erp_core.Employee'),
        ),
    ]
