# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0003_auto_20170506_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(help_text=b'Head of the Department', on_delete=django.db.models.deletion.CASCADE, related_name='department_set', to='erp_core.Employee'),
        ),
    ]
